
package co.com.hyunseda.market.presentation;

import co.com.hyunseda.market.infrastructure.Observer;
import co.com.hyunseda.market.domain.Product;
import co.com.hyunseda.market.service.CategoryService;
import co.com.hyunseda.market.service.ProductService;
import co.com.hyunseda.market.service.ShoppingCartService;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author Laura Sofia
 */
public class GUIAGREGARPRODUCT extends javax.swing.JFrame implements Observer{
    
    private CategoryService categoryService;
    private ProductService productService;
    private ShoppingCartService shoppingCartService;
    private boolean addOption = true;

    /**
     * Creates new form GUIMENUCATEGORIA
     * @param productService
     * @param shoppingCartService
     */
    public GUIAGREGARPRODUCT(CategoryService categoryService,ProductService productService,ShoppingCartService shoppingCartService) {
        
        initComponents();
       
        this.categoryService = categoryService;
        this.productService = productService;
        this.shoppingCartService = shoppingCartService;
        /*txtIdAgregarProduct.setEnabled(false);
        txtIdAgregarProduct.setEnabled(false);*/
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnRegresarMenuProducto = new javax.swing.JButton();
        btnAgregarProducto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtIdAgregarProduct = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombreAgregarProduct = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDescripAgregarProduct = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrecioAgregarProduct = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtExiAgregarProduct = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtURLImagenAgregarProduct = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCaracAgregarProduct = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCategIdAgregarProduct = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("AGREGAR PRODUCTO");
        getContentPane().add(jLabel3, java.awt.BorderLayout.PAGE_START);

        btnRegresarMenuProducto.setText("Regresar al Menu Producto");
        btnRegresarMenuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresarMenuProducto);

        btnAgregarProducto.setText("Agregar");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarProducto);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridLayout(8, 2));

        jLabel4.setText("Id:");
        jPanel2.add(jLabel4);
        jPanel2.add(txtIdAgregarProduct);

        jLabel5.setText("Nombre:");
        jPanel2.add(jLabel5);
        jPanel2.add(txtNombreAgregarProduct);

        jLabel6.setText("Descripción:");
        jPanel2.add(jLabel6);
        jPanel2.add(txtDescripAgregarProduct);

        jLabel7.setText("Precio:");
        jPanel2.add(jLabel7);
        jPanel2.add(txtPrecioAgregarProduct);

        jLabel8.setText("Existencias");
        jPanel2.add(jLabel8);
        jPanel2.add(txtExiAgregarProduct);

        jLabel9.setText("URL Imagen:");
        jPanel2.add(jLabel9);

        txtURLImagenAgregarProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtURLImagenAgregarProductActionPerformed(evt);
            }
        });
        jPanel2.add(txtURLImagenAgregarProduct);

        jLabel10.setText("Características:");
        jPanel2.add(jLabel10);
        jPanel2.add(txtCaracAgregarProduct);

        jLabel12.setText("ID Categoría:");
        jPanel2.add(jLabel12);
        jPanel2.add(txtCategIdAgregarProduct);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarMenuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuProductoActionPerformed
        GUIMENUPRODUCTO abrir = new GUIMENUPRODUCTO(categoryService,productService,shoppingCartService);
        abrir.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_btnRegresarMenuProductoActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
                                                
       
        txtNombreAgregarProduct.requestFocus();
        addOption = true;
        if (txtNombreAgregarProduct.getText().trim().equals("")) {
            Messages.showMessageDialog("Debe ingresar el nombre del producto", "Atención");
            txtNombreAgregarProduct.requestFocus();
            return;
        }
        if(addOption) {
            //Agregar
            addProduct();
        } 
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void txtURLImagenAgregarProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtURLImagenAgregarProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtURLImagenAgregarProductActionPerformed

        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnRegresarMenuProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCaracAgregarProduct;
    private javax.swing.JTextField txtCategIdAgregarProduct;
    private javax.swing.JTextField txtDescripAgregarProduct;
    private javax.swing.JTextField txtExiAgregarProduct;
    private javax.swing.JTextField txtIdAgregarProduct;
    private javax.swing.JTextField txtNombreAgregarProduct;
    private javax.swing.JTextField txtPrecioAgregarProduct;
    private javax.swing.JTextField txtURLImagenAgregarProduct;
    // End of variables declaration//GEN-END:variables

        private void cleanControls() {
        txtIdAgregarProduct.setText("");
        txtNombreAgregarProduct.setText("");
        txtDescripAgregarProduct.setText("");
        txtPrecioAgregarProduct.setText("");
        txtExiAgregarProduct.setText("");
        txtURLImagenAgregarProduct.setText("");
        txtCaracAgregarProduct.setText("");
        txtCategIdAgregarProduct.setText("");
    }
        private void stateInitial() {
        txtIdAgregarProduct.setEnabled(true);
        txtNombreAgregarProduct.setEnabled(true);
        txtDescripAgregarProduct.setEnabled(true);

    }
    

    private void addProduct() {
       
        int id = Integer.parseInt(txtIdAgregarProduct.getText());
        String name = txtNombreAgregarProduct.getText().trim();
        String description = txtDescripAgregarProduct.getText().trim();
       // productService.saveProduct(id,name,description)
       
        double price = Double.valueOf(txtPrecioAgregarProduct.getText().trim());
        int stock = Integer.valueOf(txtExiAgregarProduct.getText().trim());
        String photo = txtURLImagenAgregarProduct.getText().trim();
        String characteristics = txtCaracAgregarProduct.getText().trim();
        
        int categoryId = Integer.valueOf(txtCategIdAgregarProduct.getText().trim());
        if (productService.findProductById(id)!=null) {
            Messages.showMessageDialog("Ya existe un producto con la id ingresada", "Atención");
            //cleanControls();
        }else if (productService.saveProduct(id,name, description,price,stock,photo,characteristics,categoryId)) {
            Messages.showMessageDialog("Se grabó con éxito", "Atención");
            //cleanControls();
        } else {
            Messages.showMessageDialog("Error al grabar, lo siento mucho", "Atención");
        }
    }

    @Override
    public void update(Object o) {
        //ProductService productServiceLocal = (ProductService) o;
        /*
        mismos labels de GUIBUSPRODUCT
        */
    }
}


