/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.com.hyunseda.market.presentation;

import co.com.hyunseda.market.domain.Category;
import co.com.hyunseda.market.domain.Product;
import co.com.hyunseda.market.service.CategoryService;
import co.com.hyunseda.market.service.ProductService;
import co.com.hyunseda.market.service.ShoppingCartService;

/**
 *
 * @author Laura Sofia
 */
public class GUIEDITARPRODUCT extends javax.swing.JFrame {

    private CategoryService categoryService;
    private ProductService productService;
    private ShoppingCartService shoppingCartService;
    /**
     * Creates new form GUIMENUCATEGORIA
     */
    public GUIEDITARPRODUCT(CategoryService categoryService,ProductService productService,ShoppingCartService shoppingCartService) {
        initComponents();
        this.categoryService = categoryService;
        this.productService = productService;
        this.shoppingCartService = shoppingCartService;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnRegresarMenuProducto = new javax.swing.JButton();
        btnEditarProducto = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtIdEditarProduct = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNombreEditarProduct = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtDescripEditarProduct = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPrecioEditarProduct = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtExiEditarProduct = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtKeywordsEditarProduct = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCaracEditarProduct = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCatIdEditarProduct = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("EDITAR PRODUCTO");
        getContentPane().add(jLabel3, java.awt.BorderLayout.PAGE_START);

        btnRegresarMenuProducto.setText("Regresar al Menu Producto");
        btnRegresarMenuProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarMenuProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresarMenuProducto);

        btnEditarProducto.setText("Editar Producto");
        btnEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarProductoActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditarProducto);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridLayout(8, 2));

        jLabel4.setText("Id:");
        jPanel2.add(jLabel4);

        txtIdEditarProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEditarProductActionPerformed(evt);
            }
        });
        jPanel2.add(txtIdEditarProduct);

        jLabel5.setText("Nombre:");
        jPanel2.add(jLabel5);

        txtNombreEditarProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreEditarProductKeyTyped(evt);
            }
        });
        jPanel2.add(txtNombreEditarProduct);

        jLabel6.setText("Descripción:");
        jPanel2.add(jLabel6);
        jPanel2.add(txtDescripEditarProduct);

        jLabel7.setText("Precio:");
        jPanel2.add(jLabel7);

        txtPrecioEditarProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioEditarProductKeyTyped(evt);
            }
        });
        jPanel2.add(txtPrecioEditarProduct);

        jLabel8.setText("Stock:");
        jPanel2.add(jLabel8);

        txtExiEditarProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtExiEditarProductKeyTyped(evt);
            }
        });
        jPanel2.add(txtExiEditarProduct);

        jLabel9.setText("Keywords:");
        jPanel2.add(jLabel9);
        jPanel2.add(txtKeywordsEditarProduct);

        jLabel10.setText("Características:");
        jPanel2.add(jLabel10);
        jPanel2.add(txtCaracEditarProduct);

        jLabel11.setText("ID categoría:");
        jPanel2.add(jLabel11);

        txtCatIdEditarProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCatIdEditarProductKeyTyped(evt);
            }
        });
        jPanel2.add(txtCatIdEditarProduct);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdEditarProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEditarProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEditarProductActionPerformed

    private void btnRegresarMenuProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarMenuProductoActionPerformed
        GUIMENUPRODUCTO abrir = new GUIMENUPRODUCTO(categoryService,productService,shoppingCartService);
        abrir.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_btnRegresarMenuProductoActionPerformed

    private void btnEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarProductoActionPerformed
        
        String id = txtIdEditarProduct.getText().trim();
        if (id.equals("")) {
            Messages.showMessageDialog("Debe buscar el producto a editar", "Atención");
            txtIdEditarProduct.requestFocus();
            return;
        }
        Category newCategory = new Category();
        newCategory.setCategoryId(Integer.valueOf(txtCatIdEditarProduct.getText().trim()));
       
        int productId = Integer.parseInt(id);
        Product prod = new Product();
        prod.setProductName(txtNombreEditarProduct.getText().trim());
        prod.setProductDescripcion(txtDescripEditarProduct.getText().trim());
        
        prod.setProductPrice(Double.valueOf(txtPrecioEditarProduct.getText().trim()));
        prod.setProductStock(Integer.valueOf(txtExiEditarProduct.getText().trim()));
        prod.setKeywords(txtKeywordsEditarProduct.getText().trim());
        prod.setProductCaracteristc(txtCaracEditarProduct.getText().trim());
        prod.setCategory(newCategory);

        if (productService.editProduct(productId, prod)) {
            Messages.showMessageDialog("Se editó con éxito", "Atención");
            cleanControls();
            stateInitial();
        } else {
            Messages.showMessageDialog("Error al editar, lo siento mucho", "Atención");
        }
    
    }//GEN-LAST:event_btnEditarProductoActionPerformed

    private void txtNombreEditarProductKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreEditarProductKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreEditarProductKeyTyped

    private void txtPrecioEditarProductKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioEditarProductKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioEditarProductKeyTyped

    private void txtExiEditarProductKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExiEditarProductKeyTyped
         if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtExiEditarProductKeyTyped

    private void txtCatIdEditarProductKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCatIdEditarProductKeyTyped
        if (!Character.isDigit(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_txtCatIdEditarProductKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarProducto;
    private javax.swing.JButton btnRegresarMenuProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCaracEditarProduct;
    private javax.swing.JTextField txtCatIdEditarProduct;
    private javax.swing.JTextField txtDescripEditarProduct;
    private javax.swing.JTextField txtExiEditarProduct;
    private javax.swing.JTextField txtIdEditarProduct;
    private javax.swing.JTextField txtKeywordsEditarProduct;
    private javax.swing.JTextField txtNombreEditarProduct;
    private javax.swing.JTextField txtPrecioEditarProduct;
    // End of variables declaration//GEN-END:variables
   
    private void cleanControls() {
        txtIdEditarProduct.setText("");
        txtNombreEditarProduct.setText("");
        txtDescripEditarProduct.setText("");
    }
        private void stateInitial() {
        txtIdEditarProduct.setEnabled(false);
        txtNombreEditarProduct.setEnabled(true);
        txtDescripEditarProduct.setEnabled(true);

    }

}
