package co.com.hyunseda.market.presentation;

import co.com.hyunseda.market.domain.acess.CategoryRepository;
import co.com.hyunseda.market.service.CategoryService;
import co.com.hyunseda.market.service.ProductService;
import co.com.hyunseda.market.service.ShoppingCartService;

/**
 *
 * @author USUARIO
 */
public class GUILOGIN extends javax.swing.JFrame {
    
    //CategoryRepository categoryRepository = new CategoryRepository();
    //CategoryService categoryService = new CategoryService(categoryRepository);
    private CategoryService categoryService;
    private ProductService productService;
    private ShoppingCartService shoppingCartService;

    /**
     * Creates new form GUILOGIN
     * @param productService
     */
    /*public GUILOGIN(ProductService productService, ShoppingCartService shoppingCartService) {
        
        initComponents();
        this.productService = productService;
        this.shoppingCartService = shoppingCartService;
        this.categoryService = categoryService;
        
    }*/
    
    public GUILOGIN(CategoryService categoryService,ProductService productService, ShoppingCartService shoppingCartService) {
        
        initComponents();
        this.categoryService = categoryService;
        this.productService = productService;
        this.shoppingCartService = shoppingCartService;
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSuperAdmin = new javax.swing.JButton();
        btnAdmin = new javax.swing.JButton();
        btnEditor = new javax.swing.JButton();
        btnInvitado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INICIAR SESIÓN");
        getContentPane().add(jLabel2, java.awt.BorderLayout.PAGE_START);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.GridLayout(4, 1));

        btnSuperAdmin.setText("SuperAdministrador");
        btnSuperAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuperAdminActionPerformed(evt);
            }
        });
        jPanel2.add(btnSuperAdmin);

        btnAdmin.setText("Admininistrador");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        jPanel2.add(btnAdmin);

        btnEditor.setText("Editor");
        btnEditor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditorActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditor);

        btnInvitado.setText("Invitado");
        btnInvitado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvitadoActionPerformed(evt);
            }
        });
        jPanel2.add(btnInvitado);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuperAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuperAdminActionPerformed
        GUIMENUPRINCIPAL abrir = new GUIMENUPRINCIPAL(categoryService,productService,shoppingCartService);
        abrir.setVisible(true);
        this.setVisible(false); 
    }//GEN-LAST:event_btnSuperAdminActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:
        GUIMENUPRINCIPAL abrir = new GUIMENUPRINCIPAL(categoryService,productService,shoppingCartService);
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAdminActionPerformed

    private void btnEditorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditorActionPerformed
        // TODO add your handling code here:
        GUIMENUPRINCIPAL abrir = new GUIMENUPRINCIPAL(categoryService,productService,shoppingCartService);
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEditorActionPerformed

    private void btnInvitadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvitadoActionPerformed
        // TODO add your handling code here:
        //GUISTORE abrir = new GUISTORE(this,true,categoryService,productService,shoppingCartService);
        GUIPREVIEW abrir = new GUIPREVIEW(categoryService,productService,shoppingCartService);
        shoppingCartService.addObserver(abrir);
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnInvitadoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnEditor;
    private javax.swing.JButton btnInvitado;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSuperAdmin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
